feat: macro DeprecatedGeneric
webdoky/yari-ports pull request #34
Opened 2022-10-28 18:10 UTC by undead404

Depends on https://github.com/webdoky/content-processor/pull/2

2022-11-09 22:53 UTC, AdriandeCita commented on lib/kuma/macros/deprecated-generic.js
> +      return `<span class="notecard inline deprecated" title="${htmlEscape(
```suggestion
      return `<span class="notecard__deprecated inline" title="${htmlEscape(
```

2022-11-09 22:57 UTC, AdriandeCita commented on lib/kuma/macros/deprecated-generic.js
> +      return `<div class="notecard deprecated">
```suggestion
      return `<div class="notecard__deprecated">
```

2022-11-09 22:57 UTC, AdriandeCita commented on lib/kuma/macros/deprecated-generic.js
> +            <span class="notecard inline deprecated">${textContent}</span>
```suggestion
            <span class="notecard__deprecated inline">${textContent}</span>
```

2022-11-09 22:58 UTC, AdriandeCita commented on lib/kuma/macros/deprecated-generic.js
> +      return `<span class="notecard inline deprecated" title="${htmlEscape(
до речі, актуальні класи можна ж на сайті глянути https://webdoky.org/uk/docs/Web/CSS/-moz-outline-radius-bottomleft/

2022-11-09 22:59 UTC, AdriandeCita requested changes
Виглядає ок, є пара моментів. Ну і треба оновити відносно свіжих змін в основній гілці)

2022-12-13 13:23 UTC, undead404 commented
Треба не забути довиправляти...

2023-02-13 14:14 UTC, undead404 commented
Не використовується в наявних перекладах. Простіше переписати, коли буде потрібен, ніж повісити в код мертвим вантажем і сподіватися, що спрацює, коли буде час

2023-02-13 14:14 UTC, closed without merging