feat: macro DeprecatedBadge
webdoky/yari-ports pull request #37
Opened 2022-10-28 18:17 UTC by undead404

2022-11-30 23:31 UTC, AdriandeCita commented on lib/kuma/macros/deprecated-badge.js
> +  return `<abbr class="icon icon-deprecated" title="Нерекомендовано. Не для використання на нових вебсайтах.">
Ці класи якось задіюються у платформі?

2022-11-30 23:31 UTC, AdriandeCita commented on lib/kuma/macros/deprecated-badge.js
> +        <span class="visually-hidden">Нерекомендовано</span>
Ймовірно, ти мав на увазі щось таке
```suggestion
        <span class="sr-only">Нерекомендовано</span>
```

2022-12-13 13:23 UTC, undead404 commented on lib/kuma/macros/deprecated-badge.js
> +  return `<abbr class="icon icon-deprecated" title="Нерекомендовано. Не для використання на нових вебсайтах.">
Ні, напевне, треба замінити їх якимись іншими

2024-07-28 16:36 UTC, alinkedd requested changes

2024-07-28 16:36 UTC, alinkedd commented on lib/kuma/macros/deprecated-badge.js
> +  return `<abbr class="icon icon-deprecated" title="Нерекомендовано. Не для використання на нових вебсайтах.">
```suggestion
  return `<abbr class="icon icon-deprecated" title="Не рекомендовано. Не для використання на нових вебсайтах.">
```
- перевірити класи

2024-07-28 18:56 UTC, closed without merging