feat: macros httpheader
webdoky/yari-ports pull request #40
Opened 2022-10-29 09:10 UTC by undead404

Depends on https://github.com/webdoky/content-processor/pull/4

2022-10-29 09:11 UTC, undead404 commented
Tested: ```html
<a href=\"/uk/docs/Web/HTTP/Headers/Origin\" class=\"wd-nav-link--not-translated\" title=\"Це посилання веде на сторінку, якої ще не існує. Ймовірно, ми її ще не переклали.\"><code>Origin</code></a>
```

2022-11-02 21:13 UTC, AdriandeCita commented on lib/kuma/macros/cssinfo.js
> -  let localize = getLocalString.bind({ env: { locale: targetLocale } });
Гарна чистка, дякую!

2022-11-02 21:23 UTC, AdriandeCita commented on lib/kuma/macros/cssinfo.js
> +          var localizedString = this.callMacro(
Отакі штуки видаються дещо _misleading_, адже `getLocalString` насправді не є макросом. Проте сама ідея мати функцію `callMacro`, належну до контексту, видається цілком правильною.
Я рекомендую для таких випадків, як отут, створити окрему утилітарну функцію, яка б виконувала `call`, і, наприклад, оперувала лише змінними середовища контексту, а не передавала до утиліт такі речі, як цілий реєстр. Ну і, наприклад, назвати її якось на кшталт "withContext", абощо...

2022-11-02 21:30 UTC, AdriandeCita commented on lib/kuma/macros/cssinfo.js
> +          var localizedString = this.callMacro(
Я ще раз обдумав цю ідею, і у мене виникає підозра, що це не вдастся зробити чисто, доведеться явно передавати у функцію `this` в якомусь вигляді. З іншого боку, це має бути можливим в контейнері з макросами, приблизно отут:
![image](https://user-images.githubusercontent.com/11510394/199606246-41c164aa-fb4b-4609-a7ca-de6f7e225f2b.png)
До речі, туди ж можна винести і `callMacro`, щоб ця логіка в принципі не залежала від процесора

2022-11-02 21:33 UTC, AdriandeCita requested changes
Коментар стосовно функцій для прив'язки контексту. Плюс я поправив скрипт для запуску тестів, тож треба зілляти основну гілку і прогнати їх іще раз, там є трохи тестів до виправлення

2022-11-03 09:35 UTC, undead404 commented on lib/kuma/macros/cssinfo.js
> +          var localizedString = this.callMacro(
Я спробую таке зробити, щоб передавати в локальну функцію кусок контексту, а не його ввесь. Що ж до `callMacro`... Як ти це уявляєш... Щось типу
```context.callMacro = function callMacro() {}```?

2022-11-07 20:37 UTC, AdriandeCita commented on lib/kuma/macros/cssinfo.js
> +          var localizedString = this.callMacro(
я накидав невеличкий приклад з парою тестів, аби перевірити гіпотезу https://github.com/webdoky/yari-ports/pull/42

2022-11-07 21:19 UTC, AdriandeCita commented on lib/kuma/macros/cssinfo.js
> +          var localizedString = this.callMacro(
Відповідно, тепер немає необхідності очікувати на цю функцію з контент-процесора, можна спростити логіку там

2022-11-07 21:20 UTC, AdriandeCita commented on test/src/utils.mjs
> +  callMacro(macro, ...args) {
і немає сенсу описувати цілий клас тут, адже тепер ця функція сама інжектиться де треба https://github.com/webdoky/yari-ports/pull/42

2022-11-07 21:29 UTC, AdriandeCita commented on test/src/utils.mjs
> +  callMacro(macro, ...args) {
а-а, ні, ти вирішив замінити все загальним моком... Ну, напевне ок, мені взагалі подобалося бачити читати рядок `const kumaPorts = macros({ targetLocale: 'uk' });` і розуміти "Ага, цьому макросу потрібна лише локаль для роботи", але це питання смаку

2022-11-07 21:30 UTC, AdriandeCita commented on test/src/utils.mjs
> +  callMacro(macro, ...args) {
але саму функцію тримати тут немає сенсу

2022-11-07 21:30 UTC, AdriandeCita commented on test/src/kuma/macros/snapshots/embed-live-sample.mjs.md
> +    '<iframe class="nobutton wd--live-sample" title="examplebutton sample" id="frame_examplebutton"  width="200"  height="60" src="undefined/_sample_.examplebutton.html" ></iframe>'
Думаю, тут щось зламалося

2022-11-07 21:45 UTC, AdriandeCita commented on lib/kuma/macros/http-header.js
> +export default function HttpHeader(header, text, anchor, isTextPlain) {
Додай пліз пару тестів. Буквально один на перевірку макроса в конейнері, а другий якийсь снапшот з типовими вхідними даними

2022-11-07 21:49 UTC, AdriandeCita requested changes
Додав іще коментарів

2022-11-08 19:40 UTC, AdriandeCita commented on test/src/kuma/macros/snapshots/cssxref.mjs.md
> +    '<a href="/en-US/docs/Web/CSS/-moz-image-rect"><code>-moz-image-rect()</code></a>'
здається, тут було пропущено виправлення після копіпасти

2022-11-08 19:41 UTC, AdriandeCita commented on test/src/kuma/macros/css-info.mjs
> +    registry: {
Оце виглядає зайвим. Цей макрос не повинен залежати від реєстру

2022-11-08 19:43 UTC, AdriandeCita commented on test/src/kuma/macros/cssxref.mjs
> +    registry: {
Щось змінилося в логіці макроса? Він раніше не залежав від реєстру

2022-11-08 19:43 UTC, AdriandeCita requested changes
Є іще декілька питань

2022-11-08 20:00 UTC, undead404 commented on test/src/kuma/macros/css-info.mjs
> +    registry: {
Та ж ні, повинен

2022-11-08 20:01 UTC, undead404 commented on test/src/kuma/macros/css-info.mjs
> +    registry: {
https://github.com/webdoky/yari-ports/blob/16532936c058cf8596cee992b9505c5427de0f30/lib/kuma/macros/cssinfo.js#L51

2022-11-08 20:02 UTC, undead404 commented on test/src/kuma/macros/cssxref.mjs
> +    registry: {
https://github.com/webdoky/yari-ports/blob/16532936c058cf8596cee992b9505c5427de0f30/lib/kuma/macros/cssxref.js#L25

2022-11-08 20:02 UTC, undead404 commented on test/src/kuma/macros/snapshots/cssxref.mjs.md
> +    '<a href="/en-US/docs/Web/CSS/-moz-image-rect"><code>-moz-image-rect()</code></a>'
Я тут навмисно замінив одну функцію на іншу

2022-11-08 20:37 UTC, AdriandeCita approved these changes

2022-11-08 20:40 UTC, merged